"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.OPENCLAW_WORKER_SHIM_TARGETS = exports.OPENCLAW_WORKER_SHIM_MARKER = void 0;
exports.buildOpenClawWorkerShimContent = buildOpenClawWorkerShimContent;
exports.isGeneratedOpenClawWorkerShim = isGeneratedOpenClawWorkerShim;
exports.ensureOpenClawWorkerShims = ensureOpenClawWorkerShims;
const fs_1 = __importDefault(require("fs"));
const path_1 = __importDefault(require("path"));
exports.OPENCLAW_WORKER_SHIM_MARKER = 'Generated by Caisra. Bridges gateway-bundle.mjs worker resolution to dist/agents.';
/**
 * Header written by builds before the rename. An install that still has
 * it is ours and must be recognised as such, or the shim is treated as a
 * foreign file and never refreshed.
 */
const OPENCLAW_WORKER_SHIM_LEGACY_MARKERS = [
    'Generated by LobsterAI. Bridges gateway-bundle.mjs worker resolution to dist/agents.',
];
exports.OPENCLAW_WORKER_SHIM_TARGETS = [
    {
        shimFile: 'model-provider-auth.worker.mjs',
        targetFile: path_1.default.join('dist', 'agents', 'model-provider-auth.worker.js'),
    },
    {
        shimFile: 'code-mode.worker.mjs',
        targetFile: path_1.default.join('dist', 'agents', 'code-mode.worker.js'),
    },
    {
        shimFile: 'compaction-planning.worker.mjs',
        targetFile: path_1.default.join('dist', 'agents', 'compaction-planning.worker.js'),
    },
];
function toImportPath(filePath) {
    return filePath.split(path_1.default.sep).join('/');
}
function buildOpenClawWorkerShimContent(targetFile) {
    return [
        `// ${exports.OPENCLAW_WORKER_SHIM_MARKER}`,
        `import './${toImportPath(targetFile)}';`,
        '',
    ].join('\n');
}
function isGeneratedOpenClawWorkerShim(content) {
    return content.includes(exports.OPENCLAW_WORKER_SHIM_MARKER)
        || OPENCLAW_WORKER_SHIM_LEGACY_MARKERS.some((marker) => content.includes(marker));
}
function ensureOpenClawWorkerShims(runtimeRoot) {
    const result = {
        created: [],
        updated: [],
        unchanged: [],
        missingTargets: [],
        protectedExisting: [],
        skippedBecauseBundleMissing: false,
    };
    if (!fs_1.default.existsSync(path_1.default.join(runtimeRoot, 'gateway-bundle.mjs'))) {
        result.skippedBecauseBundleMissing = true;
        return result;
    }
    for (const target of exports.OPENCLAW_WORKER_SHIM_TARGETS) {
        const targetPath = path_1.default.join(runtimeRoot, target.targetFile);
        const shimPath = path_1.default.join(runtimeRoot, target.shimFile);
        if (!fs_1.default.existsSync(targetPath)) {
            result.missingTargets.push(target.shimFile);
            continue;
        }
        const expectedContent = buildOpenClawWorkerShimContent(target.targetFile);
        if (fs_1.default.existsSync(shimPath)) {
            const existing = fs_1.default.readFileSync(shimPath, 'utf8');
            if (existing === expectedContent) {
                result.unchanged.push(target.shimFile);
                continue;
            }
            if (!isGeneratedOpenClawWorkerShim(existing)) {
                result.protectedExisting.push(target.shimFile);
                continue;
            }
            fs_1.default.writeFileSync(shimPath, expectedContent, 'utf8');
            result.updated.push(target.shimFile);
            continue;
        }
        fs_1.default.writeFileSync(shimPath, expectedContent, 'utf8');
        result.created.push(target.shimFile);
    }
    return result;
}
//# sourceMappingURL=openclawWorkerShims.js.map