import { defineHostExtension } from "../../../internal/host-extensions.js"; import { getConfiguredBackendUrl } from "../../../shared/node/simeon-token.js"; import type { NotificationAgent } from "../../../shared/os-notification.js"; import { HostExtensions } from "../extension-ids.generated.js"; import { SandMobilePushNotifier, createSandMobilePushSender, isSandPhonePushEnabled } from "./mobile-push-notifier.js";
type NotificationHostEvent =
  | { readonly kind: "notification-baseline"; readonly agents: readonly NotificationAgent[] }
  | { readonly kind: "notification-agents"; readonly event: { readonly agents: readonly NotificationAgent[] }; readonly presence: { readonly windowFocusedAtMs?: number | null } }
  | { readonly kind: "notification-agent-upserted"; readonly event: { readonly agent: NotificationAgent }; readonly presence: { readonly windowFocusedAtMs?: number | null } }
  | { readonly kind: "notification-agent-forgotten"; readonly agentId: string };
interface NotificationHost { readonly events: { subscribe(listener: (event: NotificationHostEvent) => void): () => void }; }
// The phone's half of an agent's news (8 October 2026, `mobile-push-notifier.ts`): the box posts
// `POST /desktop/push` with its own credential, in place of the upstream app's ComputerService RPC.
export const notificationsExtension = defineHostExtension<{}, NotificationHost>({ id: HostExtensions.Notifications, dependencies: [HostExtensions.Auth], start: (context) => { if (!isSandPhonePushEnabled(process.env)) return {}; const auth = context.deps[HostExtensions.Auth] as { getAccessToken(options: { backendUrl: string }): Promise<string> }; const notifier = new SandMobilePushNotifier({ send: createSandMobilePushSender({ getBackendUrl: () => getConfiguredBackendUrl(), getAccessToken: (options) => auth.getAccessToken(options) }) }); const unsubscribe = context.host.events.subscribe((event) => { switch (event.kind) { case "notification-baseline": notifier.seedBaseline(event.agents); break; case "notification-agents": notifier.handleAgentsEvent(event.event); break; case "notification-agent-upserted": notifier.handleAgentUpsertedEvent(event.event); break; case "notification-agent-forgotten": notifier.forget(event.agentId); } }); context.onStop(unsubscribe); return {}; } });
