import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";
import { Window } from "happy-dom";
import { build } from "esbuild";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

async function loadFaces() {
  const temporary = await mkdtemp(path.join(os.tmpdir(), "caisra-agent-face-"));
  const output = path.join(temporary, "agent-face.mjs");
  await build({ entryPoints: [path.join(repoRoot, "source/shared/agent/agent-face.ts")], outfile: output, bundle: true, format: "esm", platform: "node", target: "node22", logLevel: "silent" });
  const module = await import(`${pathToFileURL(output).href}?${Date.now()}`);
  return { module, dispose: () => rm(temporary, { recursive: true, force: true }) };
}

const strip = (svg) => svg.replace(/ transform="[^"]*"/g, "");
const cutsOf = (svg) => /href="#[^"]*-cuts-([A-Za-z]+)-/.exec(svg)?.[1];
const shapeOf = (svg) => /id="[^"]*-shape-([a-z]+)-/.exec(svg)?.[1];
const colorOf = (svg) => /<use color="(#[0-9a-f]{6})"/.exec(svg)?.[1];

test("a slice face is generated offline, the same every time, from Grok's shape and colour", async () => {
  const { module, dispose } = await loadFaces();
  try {
    const { agentFace, rawFaceSvg } = module;
    const identity = { agentId: "agent-perrin", shape: "blob", color: "blue" };
    const first = agentFace(identity, { prefix: "a" });
    const again = agentFace(identity, { prefix: "a" });
    assert.equal(first.svg, again.svg);
    assert.equal(first.key, "agent-perrin|lump|1084FE");
    assert.equal(shapeOf(first.svg), "lump", "Grok's blob is the slice's lump");
    assert.equal(colorOf(first.svg), "#1084fe", "Grok's blue is the body colour");
    assert.doesNotMatch(first.svg, /<metadata|<!--|Generated by DiceBear/);
    assert.doesNotMatch(first.svg, /<rect width="100" height="100" fill=/, "no background tile");
    assert.doesNotMatch(first.svg, /<g clip-path="url\(#a-clip-/, "no canvas clip: a turning face may overflow the mark");
    assert.match(first.svg, /^<svg data-caisra-face="1" data-face-key="agent-perrin\|lump\|1084FE" preserveAspectRatio="xMidYMid meet" /);
    assert.match(first.svg, /viewBox="6 6 88 88"/);
    assert.match(rawFaceSvg(identity), /<!-- Generated by DiceBear/, "the raw output keeps its notice; only our copy is reshaped");
  } finally {
    await dispose();
  }
});

test("the shape follows Grok's shape, the colour Grok's colour, and only the cuts the agent", async () => {
  const { module, dispose } = await loadFaces();
  try {
    const { agentFace, GROK_SHAPE_TO_SLICE, GROK_AVATAR_COLORS } = module;
    const base = agentFace({ agentId: "agent-perrin", shape: "blob", color: "blue" }, { prefix: "a" });
    // A different shape for the same agent: same cuts, different body. This is
    // what the "change avatar" picker shows, one cell per shape.
    for (const [grok, slice] of Object.entries(GROK_SHAPE_TO_SLICE)) {
      const face = agentFace({ agentId: "agent-perrin", shape: grok, color: "blue" }, { prefix: "a" });
      assert.equal(shapeOf(face.svg), slice, `${grok} → ${slice}`);
      assert.equal(cutsOf(face.svg), cutsOf(base.svg), `${grok}: the agent keeps its cuts`);
      assert.equal(colorOf(face.svg), "#1084fe");
    }
    assert.equal(new Set(Object.values(GROK_SHAPE_TO_SLICE)).size, 8, "eight shapes, eight different bodies");
    // A different colour for the same agent: same body, same cuts, new paint.
    for (const [grok, hex] of Object.entries(GROK_AVATAR_COLORS)) {
      const face = agentFace({ agentId: "agent-perrin", shape: "blob", color: grok }, { prefix: "a" });
      assert.equal(colorOf(face.svg), hex.toLowerCase(), grok);
      assert.equal(shapeOf(face.svg), "lump");
      assert.equal(cutsOf(face.svg), cutsOf(base.svg));
    }
    // Two agents with the same shape and colour differ in their cuts (over a
    // roster, not necessarily between any two: there are sixteen patterns).
    const cuts = new Set();
    for (let index = 0; index < 40; index += 1) cuts.add(cutsOf(agentFace({ agentId: `agent-${index}`, shape: "blob", color: "blue" }).svg));
    assert.ok(cuts.size >= 8, `distinct cut patterns over forty agents: ${cuts.size}`);
    // Without an agent id the face is the shape and colour alone, and stable.
    const persona = agentFace({ shape: "hex", color: "red" }, { prefix: "a" });
    assert.equal(persona.key, "persona|hexagon|FF263C");
    assert.equal(strip(persona.svg), strip(agentFace({ shape: "hex", color: "red" }, { prefix: "a" }).svg));
    // A slice shape id and a hex colour are accepted as they are; junk falls back.
    assert.equal(agentFace({ shape: "arch", color: "#00c972" }).key, "persona|arch|00C972");
    assert.equal(agentFace({ shape: "nonsense", color: "pinkish" }).key, "persona|lump|seed");
  } finally {
    await dispose();
  }
});

test("every id is prefixed per instance, so two marks of one agent can share a page", async () => {
  const { module, dispose } = await loadFaces();
  try {
    const { agentFace, prefixIds } = module;
    const one = agentFace({ agentId: "agent-perrin", shape: "pebble", color: "green" });
    const two = agentFace({ agentId: "agent-perrin", shape: "pebble", color: "green" });
    assert.notEqual(one.prefix, two.prefix);
    for (const face of [one, two]) {
      const ids = [...face.svg.matchAll(/(?<![\w-])id="([^"]+)"/g)].map((match) => match[1]);
      assert.ok(ids.length >= 5, `ids: ${ids.join(", ")}`);
      assert.ok(ids.every((id) => id.startsWith(`${face.prefix}-`)), `unprefixed id in ${ids.join(", ")}`);
      const refs = [...face.svg.matchAll(/(?:href="#|url\(#)([^")]+)/g)].map((match) => match[1]);
      assert.ok(refs.length >= 5);
      assert.ok(refs.every((ref) => ids.includes(ref)), `dangling reference in ${refs.join(", ")}`);
    }
    assert.equal(prefixIds('<g id="x"/><use href="#x"/><g clip-path="url(#x)"/>', "p"), '<g id="p-x"/><use href="#p-x"/><g clip-path="url(#p-x)"/>');
  } finally {
    await dispose();
  }
});

test("the face carries the group the motion loop drives, and no eyes", async () => {
  const { module, dispose } = await loadFaces();
  try {
    const { agentFace, SLICE_SHAPES } = module;
    const window = new Window();
    try {
      for (const shape of SLICE_SHAPES) {
        const face = agentFace({ agentId: `agent-${shape}`, shape, color: "violet" }, { prefix: shape });
        window.document.body.innerHTML = face.svg;
        const svg = window.document.querySelector("svg");
        const body = svg.querySelector(".caisra-face__face");
        assert.ok(body, `${shape}: face group`);
        assert.ok(body.querySelector("use[href^='#']"), `${shape}: the placed cuts sit inside the face group`);
        assert.equal(svg.querySelector(".caisra-face__eyes"), null, `${shape}: the slice has no eyes`);
        assert.equal(svg.querySelectorAll(".caisra-face__pupil").length, 0);
      }
    } finally {
      window.close();
    }
  } finally {
    await dispose();
  }
});

test("the generator is quick enough to run on every mark", async () => {
  const { module, dispose } = await loadFaces();
  try {
    const { agentFace } = module;
    agentFace({ agentId: "warm", shape: "blob", color: "blue" });
    const started = performance.now();
    for (let index = 0; index < 100; index += 1) agentFace({ agentId: `agent-${index}`, shape: "hex", color: "red" });
    const perFace = (performance.now() - started) / 100;
    assert.ok(perFace < 5, `${perFace.toFixed(2)} ms per face`);
  } finally {
    await dispose();
  }
});
