import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";
import { Window } from "happy-dom";
import { build } from "esbuild";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

async function loadFaces() {
  const temporary = await mkdtemp(path.join(os.tmpdir(), "caisra-clay-face-"));
  const output = path.join(temporary, "clay-face.mjs");
  await build({ entryPoints: [path.join(repoRoot, "source/shared/agent/clay-face.ts")], outfile: output, bundle: true, format: "esm", platform: "node", target: "node22", logLevel: "silent" });
  const module = await import(`${pathToFileURL(output).href}?${Date.now()}`);
  return { module, dispose: () => rm(temporary, { recursive: true, force: true }) };
}

test("a clay face is generated from the agent id, offline, the same every time", async () => {
  const { module, dispose } = await loadFaces();
  try {
    const { clayFace, rawClayFaceSvg } = module;
    const first = clayFace("agent-perrin", { prefix: "a" });
    const again = clayFace("agent-perrin", { prefix: "a" });
    assert.equal(first.svg, again.svg);
    const other = clayFace("agent-juno", { prefix: "a" });
    assert.notEqual(first.svg, other.svg);
    assert.doesNotMatch(first.svg, /<metadata|<!--|Generated by DiceBear/);
    assert.doesNotMatch(first.svg, /<rect width="100" height="100" fill=/, "no background tile");
    assert.doesNotMatch(first.svg, /<g clip-path="url\(#a-clip-/, "no canvas clip: a turning face may overflow the mark");
    assert.match(first.svg, /id="a-animation-none-/, "the style's own idle animation is off");
    assert.match(first.svg, /^<svg data-caisra-face="1" data-agent-id="agent-perrin" data-eye-y="[\d.]+" preserveAspectRatio="xMidYMax meet" /);
    assert.match(first.svg, /viewBox="16 18 68 78"/);
    assert.match(rawClayFaceSvg("agent-perrin"), /<!-- Generated by DiceBear/, "the raw output keeps its notice; only our copy is reshaped");
  } finally {
    await dispose();
  }
});

test("every id is prefixed per instance, so two marks of one agent can share a page", async () => {
  const { module, dispose } = await loadFaces();
  try {
    const { clayFace, prefixIds } = module;
    const one = clayFace("agent-perrin");
    const two = clayFace("agent-perrin");
    assert.notEqual(one.prefix, two.prefix);
    for (const face of [one, two]) {
      const ids = [...face.svg.matchAll(/(?<![\w-])id="([^"]+)"/g)].map((match) => match[1]);
      assert.ok(ids.length >= 5, `ids: ${ids.join(", ")}`);
      assert.ok(ids.every((id) => id.startsWith(`${face.prefix}-`)), `unprefixed id in ${ids.join(", ")}`);
      const refs = [...face.svg.matchAll(/(?:href="#|url\(#)([^")]+)/g)].map((match) => match[1]);
      assert.ok(refs.length >= 5);
      assert.ok(refs.every((ref) => ids.includes(ref)), `dangling reference in ${refs.join(", ")}`);
    }
    assert.equal(prefixIds('<g id="x"/><use href="#x"/><g clip-path="url(#x)"/>', "p"), '<g id="p-x"/><use href="#p-x"/><g clip-path="url(#p-x)"/>');
  } finally {
    await dispose();
  }
});

test("the face carries the groups the motion loop drives", async () => {
  const { module, dispose } = await loadFaces();
  try {
    const { clayFace } = module;
    const window = new Window();
    try {
      let pupils = 0;
      for (const seed of ["agent-a", "agent-b", "agent-c", "agent-d", "agent-e", "agent-f"]) {
        const face = clayFace(seed, { prefix: seed });
        window.document.body.innerHTML = face.svg;
        const svg = window.document.querySelector("svg");
        assert.ok(svg.querySelector(".caisra-face__face"), `${seed}: face group`);
        const eyes = svg.querySelector(".caisra-face__eyes");
        assert.ok(eyes, `${seed}: eye group`);
        assert.equal(Number(eyes.getAttribute("data-eye-y")), face.eyeY);
        assert.ok(face.eyeY > 30 && face.eyeY < 80, `${seed}: eye line ${face.eyeY}`);
        assert.ok(eyes.querySelector("use[href^='#']"), `${seed}: the eye placement sits inside the eye group`);
        pupils += svg.querySelectorAll(".caisra-face__pupil").length;
      }
      assert.ok(pupils >= 6, `pupils across six faces: ${pupils}`);
    } finally {
      window.close();
    }
  } finally {
    await dispose();
  }
});

test("the generator is quick enough to run on every mark", async () => {
  const { module, dispose } = await loadFaces();
  try {
    const { clayFace } = module;
    clayFace("warm");
    const started = performance.now();
    for (let index = 0; index < 100; index += 1) clayFace(`agent-${index}`);
    const perFace = (performance.now() - started) / 100;
    assert.ok(perFace < 5, `${perFace.toFixed(2)} ms per face`);
  } finally {
    await dispose();
  }
});
