import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import createIgnore from "ignore";

import { resolvePackagedAppArtifacts } from "../scripts/lib/packaged-app.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("packaged verification authority is the selected app bundle", () => {
  const appPath = path.join(repoRoot, "dist", "Example.app");
  const artifacts = resolvePackagedAppArtifacts(appPath);
  assert.equal(artifacts.appPath, appPath);
  assert.equal(artifacts.asarPath, path.join(appPath, "Contents", "Resources", "app.asar"));
  assert.equal(artifacts.unpackedPath, `${artifacts.asarPath}.unpacked`);
  assert.notEqual(artifacts.asarPath, path.join(repoRoot, ".build", "app.asar"));
  assert.throws(() => resolvePackagedAppArtifacts(path.join(repoRoot, ".build", "app.asar")), /\.app bundle/);
});

test("publication ignore rules retain reconstructed frontend source", async () => {
  const ignoreRules = await readFile(path.join(repoRoot, ".gitignore"), "utf8");
  assert.match(ignoreRules, /^\/recovered\/$/m);
  assert.doesNotMatch(ignoreRules, /^recovered\/$/m);
  const retained = "frontend/src/recovered/ui/sand-form-primitives.css";
  const matcher = createIgnore().add(ignoreRules);
  assert.equal(matcher.ignores(retained), false, `${retained} must remain addable in a fresh repository`);
  assert.equal(matcher.ignores("recovered/generated-output.txt"), true, "root recovery output must remain ignored");
});

test("packaging ignites host and electron-main when artifact activation cannot", async () => {
  const source = await readFile(path.join(repoRoot, "scripts", "caisra-ignition-activation.mjs"), "utf8");
  assert.match(source, /export async function igniteProductionHost/);
  assert.match(source, /export async function igniteProductionElectronMain/);
  assert.match(source, /hostEntrySource\(\)/);
  assert.match(source, /electronMainEntrySource\(\)/);
  assert.match(source, /Deterministic clean-source production host/);
});

test("default packaging keeps the polished renderer and ignites the host", async () => {
  const source = await readFile(path.join(repoRoot, "scripts", "package-macos.mjs"), "utf8");
  const activation = await readFile(path.join(repoRoot, "scripts", "clean-build.mjs"), "utf8");
  assert.match(source, /import \{ buildFidelityReconstructedAsar \} from "\.\/clean-build\.mjs"/);
  assert.match(source, /await buildFidelityReconstructedAsar\(\)/);
  assert.doesNotMatch(source, /import \{ buildReconstructedAsar \}/);
  assert.match(activation, /igniteProductionHost/);
  assert.match(activation, /igniteProductionElectronMain/);
});

test("the Dock icon is icon.icns, so the shell's asset catalogue must not be named", async () => {
  const packager = await readFile(path.join(repoRoot, "scripts", "package-macos.mjs"), "utf8");
  const icnsAt = packager.indexOf('if (name.endsWith(".icns")) await cp(dockIcon');
  const removeAt = packager.indexOf('"-remove", "CFBundleIconName"');
  const signAt = packager.indexOf("await signAppBundleAdHoc(outputApp)");
  assert.ok(icnsAt > 0 && removeAt > icnsAt && signAt > removeAt, "the key is removed after the icon is written and before signing");
  const verify = await readFile(path.join(repoRoot, "scripts", "verify.mjs"), "utf8");
  assert.match(verify, /plistText\.includes\("CFBundleIconName"\)\) throw/);
});

test("Router settings use the trusted backend and display recorded inference usage", async () => {
  const rendererPatch = await readFile(path.join(repoRoot, "scripts", "lib", "router-renderer-patch.mjs"), "utf8");
  const preload = await readFile(path.join(repoRoot, "source", "electron-preload", "preload.ts"), "utf8");
  const mainEdge = await readFile(path.join(repoRoot, "source", "electron-main", "main-edge.ts"), "utf8");
  const inference = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "inference-service.ts"), "utf8");
  const cursorSession = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "cursor-session.ts"), "utf8");
  const cursorBackend = await readFile(path.join(repoRoot, "source", "shared", "node", "cursor-backend", "cursor-inference.ts"), "utf8");
  const providers = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "provider-session.ts"), "utf8");
  const codexDirect = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "codex-direct-responses.ts"), "utf8");
  const turnShell = await readFile(path.join(repoRoot, "source", "host", "runner", "turn-run-shell.ts"), "utf8");
  const coordinator = await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "inference-router.ts"), "utf8");
  const widgetResponses = await readFile(path.join(repoRoot, "source", "host", "extensions", "transcript", "widget-responses.ts"), "utf8");
  const gateway = await readFile(path.join(repoRoot, "source", "host", "host-gateway-api.ts"), "utf8");
  const coordinatorMain = await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "main.ts"), "utf8");
  const mcpBridge = await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "routed-mcp-bridge.ts"), "utf8");
  const localDocker = await readFile(path.join(repoRoot, "source", "electron-main", "box", "local-docker-host-connector.ts"), "utf8");
  const sharedRouter = await readFile(path.join(repoRoot, "source", "shared", "inference-router.ts"), "utf8");
  assert.doesNotMatch(rendererPatch, /id:"router",label:"Router"/);
  assert.match(rendererPatch, /export function patchOriginalSettingsPanel\(source\) \{\n  return source;\n\}/);
  assert.doesNotMatch(rendererPatch, /settings\.router-provider\.v1/);
  assert.match(preload, /getInferenceRouter: \(\) => edge\("getInferenceRouter"\)/);
  assert.match(preload, /getBoxRuntime: \(\) => edge\("getBoxRuntime"\)/);
  assert.match(preload, /setBoxRuntime: \(mode: string\) => edge\("setBoxRuntime", \{ mode \}\)/);
  assert.match(mainEdge, /const provider = resolveProductInferenceProvider\(\)/);
  assert.match(mainEdge, /syncHostSettingsToBox\(\{ inferenceProvider: provider \}\)/);
  assert.match(mainEdge, /invoke\(deps\.settingsStore, "setInferenceProvider", provider\)/);
  assert.match(mainEdge, /return \{ provider, usage:/);
  assert.match(mainEdge, /invoke\(deps\.boxRecovery, "restartCoordinator"\)/);
  // "remote" is probed through the box recovery before the local box is stopped (25 September 2026).
  assert.match(mainEdge, /mode === "local-docker"\) await startLocalDockerBox\(settingsPath\); else \{ await Promise\.resolve\(invoke\(deps\.boxRecovery, "probeRemoteBox"\)\); await stopLocalDockerBox\(\); \}/);
  assert.match(mainEdge, /setBoxRuntime", mode === "local-docker" \? "remote" : "local-docker"/);
  assert.match(localDocker, /public\.ecr\.aws\/k0i0n2g5\/cursorenvironments\/universal:sand-box-latest/);
  assert.match(localDocker, /"127\.0\.0\.1:1340:1340"/);
  assert.match(localDocker, /SAND_BOX_AUTO_UPDATE=0/);
  assert.match(localDocker, /dst=\/home\/box\/sand-host\/host-main\.cjs,readonly/);
  assert.match(localDocker, /\.getBoxRuntime\(\) === "local-docker" \? await localConnect\(\) : await remote\.connect\(\)/);
  assert.match(localDocker, /OPTIONAL_CREDENTIAL_WAIT_MS = 250/);
  assert.match(localDocker, /localDockerContainerNeedsReplace\(inspected, hostBundle\.sha256, streamTokenSha256\)/);
  assert.doesNotMatch(localDocker, /inferenceCredential != null && !inspected\.hasInferenceCredential/);
  assert.match(inference, /recordInferenceUsage\(provider/);
  assert.match(inference, /routerSettings\.getInferenceProvider\(\)/);
  assert.match(inference, /typeof extendedUsage\.then === "function"/);
  assert.match(inference, /createProviderPromptSession\(provider, sessionOptions, onRequestId\)/);
  assert.match(providers, /https:\/\/chatgpt\.com\/backend-api\/codex/);
  assert.match(providers, /headers\.set\("ChatGPT-Account-Id", credentials\.accountId\)/);
  assert.match(providers, /streamCodexDirectResponses/);
  assert.doesNotMatch(providers, /provider\.responses\(configuredCodexModel\(\)\)/);
  assert.match(codexDirect, /store: false/);
  assert.match(codexDirect, /response\.output_text\.delta/);
  assert.match(codexDirect, /type: "function_call_output"/);
  assert.match(providers, /parameters: jsonSchema\(parameters\)/);
  assert.match(providers, /You are Simeon, a warm, concise desktop assistant/);
  assert.match(providers, /mcpServers: \{ grok_bot_plugins:/);
  assert.match(providers, /recordRoutedUsage\(provider, usage\)/);
  assert.match(providers, /queryClaude/);
  assert.match(providers, /tools: mcpServerUrl == null \? \[\] : \["mcp__grok_bot_plugins__\*"\]/);
  assert.match(providers, /https:\/\/openrouter\.ai\/api\/v1/);
  assert.match(providers, /OpenRouter needs OPENROUTER_API_KEY/);
  assert.match(cursorSession, /routedProvider !== "cursor"/);
  assert.match(cursorSession, /createProviderPromptSession\(routedProvider, sessionOptions\)/);
  assert.match(cursorBackend, /routedProvider !== "cursor"/);
  assert.match(cursorBackend, /createProviderPromptSession\(routedProvider, \{ modelId: options\.requestedModel\.modelId \}\)/);
  assert.doesNotMatch(rendererPatch, /ANTHROPIC_API_KEY|OPENAI_API_KEY/);
  assert.match(turnShell, /const inferenceProvider = "claidor"/);
  assert.match(turnShell, /createProviderPromptSession\(inferenceProvider, \{ \.\.\.sessionOptions, hidden \}\)/);
  assert.match(coordinator, /method !== "sendPrompt" \|\| !handledLocally\(provider\)/);
  assert.match(coordinator, /method === "respondToWidget" && handledLocally\(provider\)/);
  assert.match(coordinator, /skipTurn: true/);
  assert.match(coordinator, /appendUserMessage !== false/);
  assert.match(coordinator, /provider !== "cursor" && !\(provider === "claidor" && routesClaidorThroughHost\(options\.env\)\)/);
  assert.match(coordinator, /provider\(\): SandInferenceProvider \{ return resolveProductInferenceProvider\(options\.env \?\? process\.env\); \}/);
  assert.match(coordinator, /STORED_PROVIDERS\.includes\(String\(row\.provider\)\)/);
  assert.match(coordinatorMain, /command<[^>]*>\(commands, "mintInferenceCredential", \{\}\)/);
  assert.match(providers, /\.responses\(id\)/);
  assert.match(providers, /DEFAULT_CLAIDOR_CHEAP_MODEL = "gpt-5\.6-luna"/);
  assert.match(providers, /export function claidorModelForSession/);
  assert.match(inference, /cheap: true, isSummarizationSession: true/);
  assert.match(turnShell, /cheap: true, isSummarizationSession: true/);
  assert.match(providers, /providerOptions: \{ openai: \{ strictSchemas: false, \.\.\.openaiOptions \} \}/);
  assert.match(providers, /from "\.\.\/\.\.\/\.\.\/shared\/node\/cursor-backend\/claidor-api\.js"/);
  assert.match(providers, /export \{ claidorProxyBaseUrl \}/);
  assert.match(await readFile(path.join(repoRoot, "source", "shared", "node", "cursor-backend", "claidor-api.ts"), "utf8"), /CLAIDOR_PROXY_PREFIX = "desktop\/api\/proxy\/v1"/);
  assert.match(providers, /headers\.set\("authorization", `Bearer \$\{accessToken\}`\)/);
  assert.match(inference, /setClaidorCredentialSource\(\{ getAccessToken: \(\) => auth\.getAccessToken\(\) \}\)/);
  assert.match(coordinator, /export const BOX_OPTIONAL_WAIT_MS = 800/);
  assert.match(sharedRouter, /export const SAND_CLAIDOR_FULL_AGENT_ENV = "SAND_CLAIDOR_FULL_AGENT"/);
  assert.match(sharedRouter, /if \(raw\.length === 0\) return true/);
  assert.match(sharedRouter, /return !envFlagDisabled\(raw\)/);
  assert.match(coordinator, /export \{ SAND_CLAIDOR_FULL_AGENT_ENV, routesClaidorThroughHost \}/);
  assert.match(coordinator, /GROK_BOT_TOOLS/);
  assert.match(coordinator, /isGrokBotToolName/);
  assert.match(coordinator, /executeRoutedAgentTool/);
  assert.match(coordinator, /mergeHostAndLocalChatHistory/);
  assert.match(gateway, /executeRoutedAgentTool/);
  assert.match(gateway, /appendSendMessage: messageArgs => method\(manager, "appendSendMessage"\)/);
  assert.match(gateway, /authorize: \(scope, request\) => method\(localToolPermission, "authorize"\)/);
  assert.match(await readFile(path.join(repoRoot, "source", "host", "gateway-protocol.ts"), "utf8"), /executeRoutedAgentTool/);
  assert.match(await readFile(path.join(repoRoot, "source", "shared", "grok-bot-tools.ts"), "utf8"), /"ExternalShell"/);
  assert.match(await readFile(path.join(repoRoot, "source", "shared", "grok-bot-tools.ts"), "utf8"), /"ExternalRead"/);
  assert.match(await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "gateway", "gateway-client.ts"), "utf8"), /SAND_ENABLE_SLIM_AVATARS/);
  assert.match(await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "gateway", "gateway-client.ts"), "utf8"), /if \(this\.slimAvatarsEnabled\) headers\[GATEWAY_SLIM_AVATARS_HEADER\] = "1"/);
  assert.doesNotMatch(await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "gateway", "gateway-client.ts"), "utf8"), /SAND_DISABLE_SLIM_AVATARS/);
  assert.match(providers, /CLAIDOR_FETCH_TIMEOUT_MS = 45_000/);
  assert.match(providers, /Timed out waiting for a Simeon sign-in/);
  assert.match(await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "gateway", "gateway-client.ts"), "utf8"), /connectDeadline\.run\(\(signal\) => this\.resolveConnection\(signal\)\)/);
  assert.match(coordinator, /executeTool: async \(definition, toolArgs, toolCallId\)/);
  assert.match(coordinatorMain, /command\(commands, "listRoutedMcpTools", args\)/);
  assert.match(coordinator, /inference-router-transcript\.json/);
  assert.match(mcpBridge, /openWorldHint: !readOnly/);
  assert.match(coordinator, /schemaVersion: 2/);
  assert.match(coordinator, /\["getAgentTranscriptTail", "openAgentTail", "getAgentTranscriptWindow"\]/);
  assert.match(coordinator, /visibleLocalEntries/);
  assert.match(coordinator, /\.filter\(entry => entry\.hidden !== true\)\.map\(projectInferenceRouterTranscriptEntry\)/);
  assert.match(coordinator, /readonly richText\?: string/);
  assert.match(coordinator, /richText: entry\.richText/);
  assert.match(coordinator, /setTimeout\(resolve, 1_200\)/);
  assert.match(coordinator, /method === "reactToMessage"/);
  assert.match(coordinator, /reaction\.by === "me"/);
  assert.match(coordinator, /currentActivity: \{ kind: "thinking" \}/);
  assert.match(coordinator, /buildSandProductSystemPrompt/);
  assert.match(coordinator, /postEvent\("agents"/);
  assert.match(widgetResponses, /options\?\.skipTurn === true/);
  assert.match(gateway, /args\.skipTurn === true \? \{ skipTurn: true \}/);
  assert.match(coordinator, /createRoutedMcpBridge/);
  assert.match(coordinator, /listRoutedMcpTools/);
  assert.match(coordinator, /executeRoutedMcpTool/);
  assert.match(mcpBridge, /server\.listen\(0, "127\.0\.0\.1"/);
  assert.match(mcpBridge, /readOnlyHint: readOnly/);
  assert.match(mcpBridge, /request\.url !== `\/mcp\/\$\{secret\}`/);
  assert.match(coordinator, /kind: "send-message"/);
  assert.match(coordinatorMain, /createCoordinatorInferenceRouter/);
  assert.match(coordinatorMain, /routed\.handled/);
});
