/**
 * Does Rakazo's own client accept the shapes Claidor's proxy serves?
 *
 * Not a mock of Rakazo. This imports Rakazo's real adapter code and points
 * it at a stand-in of `/desktop/api/proxy/v1` answering exactly what
 * `server/polar/desktop/endpoints.py` answers — same list, same bearer
 * check, same wire/provider agreement rule. The list is not copied here:
 * it is generated by Claidor's own `openai_models_list`, so the two cannot
 * drift apart without this check noticing.
 *
 * It exists because the server's own test suite needs Postgres and a final
 * Python 3.14, and this needs neither — it is the offline half of the
 * evidence, in the spirit of `rakazo/docs/agent-verification.md`.
 *
 *     cd <repo root>
 *     rakazo/node_modules/.bin/tsx scripts/rakazo/wire-check.mts
 *
 * Nothing here writes to `rakazo/`, which is the pristine fork.
 */
import { createServer } from "node:http";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  probeOpenAiCompatibleModels,
  prepareOpenAiCompatibleConnect,
} from "../../rakazo/packages/adapters/src/pi-openai-compatible-provider.js";
import { normalizeOpenAiCompatibleBaseUrl } from "../../rakazo/packages/adapters/src/openai-compatible-url.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const SERVER = join(ROOT, "server");

/**
 * The menu, from the price module itself.
 *
 * `polar/desktop/pricing.py` imports nothing but the standard library, so
 * any Python runs it — which is the whole reason the catalogue was split
 * out of `service.py`. `offered_models()` does live in `service.py` and
 * needs settings, so its two filters are applied here instead: a role, and
 * a configured provider (both provider keys assumed present).
 */
function modelsList(): { object: string; data: { id: string }[] } {
  const venv = join(SERVER, ".venv", "bin", "python");
  const python = existsSync(venv) ? venv : "python3";
  const source = [
    "import json, sys",
    "from polar.desktop.pricing import MODELS, SpokenApi, openai_models_list",
    "offered = [one for one in MODELS if one.role is not None]",
    "print(json.dumps(openai_models_list(offered, SpokenApi.openai_completions)))",
  ].join("\n");
  const out = execFileSync(python, ["-c", source], { cwd: SERVER, encoding: "utf8" });
  return JSON.parse(out);
}

const MODELS_LIST = modelsList();
const OPENAI_MODELS = MODELS_LIST.data.map((one) => one.id);
const ANTHROPIC_MODEL = "claude-sonnet-5";

const seen: { path: string; auth: string | undefined; body?: string }[] = [];

const claidor = createServer((req, res) => {
  const url = new URL(req.url ?? "/", "http://127.0.0.1");
  const auth = req.headers.authorization;
  let body = "";
  req.on("data", (chunk) => {
    body += chunk;
  });
  req.on("end", () => {
    seen.push({ path: url.pathname, auth, body: body || undefined });
    const send = (status: number, payload: unknown) => {
      res.writeHead(status, { "content-type": "application/json" });
      res.end(JSON.stringify(payload));
    };
    // polar/desktop/auth.py: one bearer, or nothing.
    if (auth !== "Bearer claidor_pat_test") {
      return send(401, { error: { type: "unauthorized", message: "Sign in." } });
    }
    // polar/desktop/endpoints.py, proxy_models. Note: NOT the desktop
    // app's {"code":0,"data":…} envelope.
    if (url.pathname.endsWith("/models")) {
      return send(200, MODELS_LIST);
    }
    if (url.pathname.endsWith("/chat/completions")) {
      const asked = JSON.parse(body || "{}").model;
      // endpoints.py:_proxy — the model's provider must speak this wire.
      if (asked === ANTHROPIC_MODEL) {
        return send(400, {
          error: {
            type: "invalid_request_error",
            message: `${asked} is served by anthropic and is not reached through the openai-completions API.`,
          },
        });
      }
      return send(200, {
        id: "c1",
        choices: [{ message: { role: "assistant", content: "Hello" } }],
        usage: { prompt_tokens: 10, completion_tokens: 2 },
      });
    }
    // endpoints.py, proxy_other.
    return send(404, {
      error: { type: "not_found_error", message: "not proxied." },
    });
  });
});

const ok = (name: string) => console.log(`  ok  ${name}`);

await new Promise<void>((done) => claidor.listen(0, "127.0.0.1", done));
const port = (claidor.address() as { port: number }).port;
const base = `http://127.0.0.1:${port}/desktop/api/proxy/v1`;

try {
  // 1. The base URL survives their normaliser unchanged. It ends in /v1,
  //    so nothing is appended -- this is the line that would silently turn
  //    .../proxy into .../proxy/v1 and quietly work, or not.
  assert.equal(normalizeOpenAiCompatibleBaseUrl(base), base);
  ok("the base URL passes through normalizeOpenAiCompatibleBaseUrl unchanged");

  // 2. Their Connect step accepts it with a key.
  const prepared = prepareOpenAiCompatibleConnect({
    provider: "openai-compatible",
    baseUrl: base,
    modelId: "gpt-5.6-luna",
    apiKey: "claidor_pat_test",
  });
  assert.equal(prepared.baseUrl, base);
  assert.equal(prepared.apiKey, "claidor_pat_test");
  ok("prepareOpenAiCompatibleConnect accepts the base URL, model id and key");

  // 3. Their probe reads our list. This is the call that answered 404
  //    before the route existed.
  const ids = await probeOpenAiCompatibleModels({
    baseUrl: base,
    apiKey: "claidor_pat_test",
  });
  assert.deepEqual(ids, OPENAI_MODELS);
  assert.ok(ids.length > 0, "Claidor must offer at least one model here");
  assert.ok(!ids.includes(ANTHROPIC_MODEL), "Claude is not on this wire");
  ok(`probeOpenAiCompatibleModels found ${ids.join(", ")}`);

  const probe = seen.find((one) => one.path.endsWith("/models"));
  assert.equal(probe?.path, "/desktop/api/proxy/v1/models");
  assert.equal(probe?.auth, "Bearer claidor_pat_test");
  ok("it GETs <base>/models with the key as a Bearer");

  // 4. Without the key, our 401 reaches them as a refusal they can show.
  await assert.rejects(
    probeOpenAiCompatibleModels({ baseUrl: base }),
    /401/,
    "an unauthenticated probe should surface the 401",
  );
  ok("an unauthenticated probe surfaces the 401");

  // 5. The public-host gate, which is the one line of deployment config
  //    the connection needs. api.claidor.com is a public name.
  const publicBase = "https://api.claidor.com/desktop/api/proxy/v1";
  delete process.env.RAKAZO_OPENAI_COMPAT_ALLOW_PUBLIC;
  assert.throws(
    () =>
      prepareOpenAiCompatibleConnect({
        provider: "openai-compatible",
        baseUrl: publicBase,
        modelId: "gpt-5.6-luna",
        apiKey: "claidor_pat_test",
      }),
    /RAKAZO_OPENAI_COMPAT_ALLOW_PUBLIC/,
    "a public host should be refused without the gate",
  );
  ok("api.claidor.com is refused without RAKAZO_OPENAI_COMPAT_ALLOW_PUBLIC=1");

  process.env.RAKAZO_OPENAI_COMPAT_ALLOW_PUBLIC = "1";
  const live = prepareOpenAiCompatibleConnect({
    provider: "openai-compatible",
    baseUrl: publicBase,
    modelId: "gpt-5.6-luna",
    apiKey: "claidor_pat_test",
  });
  assert.equal(live.baseUrl, publicBase);
  ok("with the gate set, api.claidor.com is accepted");

  // 6. And http:// with a key is refused whatever the gate says, which is
  //    why the connection is documented as https only.
  assert.throws(
    () =>
      prepareOpenAiCompatibleConnect({
        provider: "openai-compatible",
        baseUrl: "http://api.claidor.com/desktop/api/proxy/v1",
        modelId: "gpt-5.6-luna",
        apiKey: "claidor_pat_test",
      }),
    /HTTPS/,
    "http with a key should be refused",
  );
  ok("http:// with a key is refused even with the gate set");

  console.log("\nall checks passed");
} finally {
  claidor.close();
}
