// Generated by ios/scripts/make-assets.mjs from desktop/brand and the Mac
// window's patch (router-renderer-patch.mjs). Do not edit by hand.

/** An app a message can name: the spelling, its logo's key, its colour in light and dark, and whether its logo is one colour (tinted like the name). */
public struct BrandMention: Sendable, Hashable {
  public let name: String
  public let key: String
  public let light: String
  public let dark: String
  public let mono: Bool
}

public enum Brands {
  /** Every spelling, longest first, as the Mac matches them. */
  public static let mentions: [BrandMention] = [
    BrandMention(name: "Microsoft PowerPoint", key: "powerpoint", light: "#c43e1c", dark: "#d67860", mono: false),
    BrandMention(name: "Microsoft Outlook", key: "outlook", light: "#0078d4", dark: "#3393dd", mono: false),
    BrandMention(name: "Google Calendar", key: "google-calendar", light: "#4285f4", dark: "#4b8bf5", mono: false),
    BrandMention(name: "Microsoft Excel", key: "excel", light: "#107c41", dark: "#4c9d71", mono: false),
    BrandMention(name: "Microsoft Word", key: "word", light: "#185abd", dark: "#6994d4", mono: false),
    BrandMention(name: "Google Sheets", key: "google-sheets", light: "#0f9d58", dark: "#1ba260", mono: false),
    BrandMention(name: "Google Slides", key: "google-slides", light: "#ab7e00", dark: "#f4b400", mono: false),
    BrandMention(name: "Google Drive", key: "google-drive", light: "#1d9c5e", dark: "#1fa463", mono: false),
    BrandMention(name: "Google Docs", key: "google-docs", light: "#4285f4", dark: "#4b8bf5", mono: false),
    BrandMention(name: "Google Meet", key: "google-meet", light: "#00897b", dark: "#33a195", mono: false),
    BrandMention(name: "Cloudflare", key: "cloudflare", light: "#cf6d1b", dark: "#f38020", mono: true),
    BrandMention(name: "Databricks", key: "databricks", light: "#ff3621", dark: "#ff4a37", mono: true),
    BrandMention(name: "Greenhouse", key: "greenhouse", light: "#209472", dark: "#24a47f", mono: true),
    BrandMention(name: "PowerPoint", key: "powerpoint", light: "#c43e1c", dark: "#d67860", mono: false),
    BrandMention(name: "QuickBooks", key: "quickbooks", light: "#2a981b", dark: "#37a527", mono: true),
    BrandMention(name: "Salesforce", key: "salesforce", light: "#0091ca", dark: "#00a1e0", mono: true),
    BrandMention(name: "Instagram", key: "instagram", light: "#ff0069", dark: "#ff408f", mono: true),
    BrandMention(name: "Mailchimp", key: "mailchimp", light: "#241c15", dark: "#ececec", mono: false),
    BrandMention(name: "Pinterest", key: "pinterest", light: "#bd081c", dark: "#d76b77", mono: true),
    BrandMention(name: "Snowflake", key: "snowflake", light: "#2191ba", dark: "#29b5e8", mono: true),
    BrandMention(name: "WordPress", key: "wordpress", light: "#21759b", dark: "#5998b4", mono: true),
    BrandMention(name: "Airtable", key: "airtable", light: "#128fbf", dark: "#18bfff", mono: true),
    BrandMention(name: "Calendly", key: "calendly", light: "#006bff", dark: "#4090ff", mono: true),
    BrandMention(name: "Evernote", key: "evernote", light: "#009729", dark: "#00a82d", mono: true),
    BrandMention(name: "Facebook", key: "facebook", light: "#0866ff", dark: "#468cff", mono: true),
    BrandMention(name: "Intercom", key: "intercom", light: "#3a8b83", dark: "#6afdef", mono: true),
    BrandMention(name: "LinkedIn", key: "linkedin", light: "#0a66c2", dark: "#5394d4", mono: true),
    BrandMention(name: "Obsidian", key: "obsidian", light: "#7c3aed", dark: "#a375f2", mono: true),
    BrandMention(name: "Substack", key: "substack", light: "#e65d16", dark: "#ff6719", mono: true),
    BrandMention(name: "Supabase", key: "supabase", light: "#2f9b6b", dark: "#3fcf8e", mono: true),
    BrandMention(name: "Telegram", key: "telegram", light: "#208cc2", dark: "#26a5e4", mono: true),
    BrandMention(name: "Typeform", key: "typeform", light: "#262627", dark: "#ececec", mono: true),
    BrandMention(name: "WhatsApp", key: "whatsapp", light: "#1a9447", dark: "#25d366", mono: true),
    BrandMention(name: "ClickUp", key: "clickup", light: "#7b68ee", dark: "#8f7ff1", mono: true),
    BrandMention(name: "Discord", key: "discord", light: "#5865f2", dark: "#7984f5", mono: true),
    BrandMention(name: "Dropbox", key: "dropbox", light: "#0061ff", dark: "#4d90ff", mono: true),
    BrandMention(name: "HubSpot", key: "hubspot", light: "#cc6247", dark: "#ff7a59", mono: true),
    BrandMention(name: "Outlook", key: "outlook", light: "#0078d4", dark: "#3393dd", mono: false),
    BrandMention(name: "Postman", key: "postman", light: "#d95c2f", dark: "#ff6c37", mono: true),
    BrandMention(name: "Revolut", key: "revolut", light: "#191c1f", dark: "#ececec", mono: true),
    BrandMention(name: "Shopify", key: "shopify", light: "#62914a", dark: "#7ab55c", mono: true),
    BrandMention(name: "Spotify", key: "spotify", light: "#159743", dark: "#1ed760", mono: true),
    BrandMention(name: "Tableau", key: "tableau", light: "#d26a23", dark: "#e97627", mono: true),
    BrandMention(name: "Todoist", key: "todoist", light: "#e44332", dark: "#e9695b", mono: true),
    BrandMention(name: "Webflow", key: "webflow", light: "#146ef5", dark: "#438bf7", mono: true),
    BrandMention(name: "YouTube", key: "youtube", light: "#ff0000", dark: "#ff4d4d", mono: true),
    BrandMention(name: "Zendesk", key: "zendesk", light: "#03363d", dark: "#ececec", mono: true),
    BrandMention(name: "Airbnb", key: "airbnb", light: "#e65156", dark: "#ff5a5f", mono: true),
    BrandMention(name: "Framer", key: "framer", light: "#0055ff", dark: "#4d88ff", mono: true),
    BrandMention(name: "GitHub", key: "github", light: "#181717", dark: "#ececec", mono: true),
    BrandMention(name: "Linear", key: "linear", light: "#5e6ad2", dark: "#7e88db", mono: true),
    BrandMention(name: "Notion", key: "notion", light: "#000000", dark: "#ececec", mono: true),
    BrandMention(name: "Paddle", key: "paddle", light: "#988520", dark: "#fddd35", mono: true),
    BrandMention(name: "PayPal", key: "paypal", light: "#003087", dark: "#738dbd", mono: true),
    BrandMention(name: "Reddit", key: "reddit", light: "#f24200", dark: "#ff4e0d", mono: true),
    BrandMention(name: "Sentry", key: "sentry", light: "#362d59", dark: "#908ca4", mono: true),
    BrandMention(name: "Stripe", key: "stripe", light: "#635bff", dark: "#827cff", mono: true),
    BrandMention(name: "TikTok", key: "tiktok", light: "#000000", dark: "#ececec", mono: true),
    BrandMention(name: "Trello", key: "trello", light: "#0052cc", dark: "#598fde", mono: true),
    BrandMention(name: "Twilio", key: "twilio", light: "#f22f46", dark: "#f5596b", mono: true),
    BrandMention(name: "Vercel", key: "vercel", light: "#000000", dark: "#ececec", mono: true),
    BrandMention(name: "Zapier", key: "zapier", light: "#f24b00", dark: "#ff4f00", mono: true),
    BrandMention(name: "Asana", key: "asana", light: "#d85f5f", dark: "#f06a6a", mono: true),
    BrandMention(name: "Brevo", key: "brevo", light: "#0b996e", dark: "#23a37d", mono: true),
    BrandMention(name: "Canva", key: "canva", light: "#009399", dark: "#00c4cc", mono: true),
    BrandMention(name: "Excel", key: "excel", light: "#107c41", dark: "#4c9d71", mono: false),
    BrandMention(name: "Figma", key: "figma", light: "#f24e1e", dark: "#f36035", mono: true),
    BrandMention(name: "Gmail", key: "gmail", light: "#ea4335", dark: "#ed5f53", mono: false),
    BrandMention(name: "Gusto", key: "gusto", light: "#e85844", dark: "#f45d48", mono: true),
    BrandMention(name: "Slack", key: "slack", light: "#4a154b", dark: "#ececec", mono: false),
    BrandMention(name: "Jira", key: "jira", light: "#0052cc", dark: "#598fde", mono: true),
    BrandMention(name: "Loom", key: "loom", light: "#625df5", dark: "#8985f8", mono: true),
    BrandMention(name: "Miro", key: "miro", light: "#050038", dark: "#ececec", mono: true),
    BrandMention(name: "Xero", key: "xero", light: "#0f91bb", dark: "#13b5ea", mono: true),
    BrandMention(name: "Zoom", key: "zoom", light: "#0b5cff", dark: "#548dff", mono: false),
  ]

  /** An agent's name colour in a message, by palette (the palette's top stop, made readable on the bubble). */
  public static let agentNameColours: [String: (light: String, dark: String)] = [
    "yellow": (light: "#7d7dd3", dark: "#8b8bea"),
    "cyan": (light: "#2f6f72", dark: "#6d9a9c"),
    "violet": (light: "#5d90a8", dark: "#7cc0e0"),
    "red": (light: "#bf7359", dark: "#ff9a76"),
    "green": (light: "#6f8f4f", dark: "#7d9a61"),
    "brown": (light: "#877c6c", dark: "#f6e2c4"),
    "magenta": (light: "#be688f", dark: "#e07aa8"),
    "blue": (light: "#1f3b73", dark: "#8493b2"),
    "gray": (light: "#a07d81", dark: "#f6c1c7"),
    "black": (light: "#77859c", dark: "#8c9db8"),
    "orange": (light: "#997d64", dark: "#ffd1a6"),
    "mint": (light: "#69847c", dark: "#bff0e2"),
  ]
}
