"""playbooks

Revision ID: 65b8da6b66c8
Revises: registry_harvest_0809
Create Date: 2026-08-09 22:36:44.213590

Written by hand rather than autogenerated. The autogenerated version also
wanted to drop the pg_trgm extension and dozens of indexes and constraints
across unrelated tables — dossiers, veilles, court_decisions, the email
tables — which is pre-existing drift between the models and this database
rather than anything to do with playbooks. Shipping it would have deleted
working indexes on tables this change never touches.

Only the two new tables are here.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "65b8da6b66c8"
down_revision = "registry_harvest_0809"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    op.create_table(
        "playbooks",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("contract_type", sa.String(length=160), nullable=False),
        sa.Column("side", sa.String(length=40), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("playbooks_organization_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("playbooks_pkey")),
        sa.UniqueConstraint("organization_id", "name", name="playbooks_org_name_key"),
    )
    op.create_index(
        "ix_playbooks_organization_id", "playbooks", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_playbooks_created_at"), "playbooks", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_playbooks_deleted_at"), "playbooks", ["deleted_at"], unique=False
    )

    op.create_table(
        "playbook_rules",
        sa.Column("playbook_id", sa.Uuid(), nullable=False),
        sa.Column("clause", sa.String(length=200), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("preferred", sa.Text(), nullable=False),
        sa.Column("acceptable", sa.Text(), nullable=True),
        sa.Column("fallback", sa.Text(), nullable=True),
        sa.Column("walk_away", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("approval", sa.String(length=20), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["playbook_id"],
            ["playbooks.id"],
            name=op.f("playbook_rules_playbook_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("playbook_rules_pkey")),
        sa.UniqueConstraint("playbook_id", "clause", name="playbook_rules_clause_key"),
    )
    op.create_index(
        "ix_playbook_rules_playbook_id", "playbook_rules", ["playbook_id"], unique=False
    )
    op.create_index(
        op.f("ix_playbook_rules_created_at"),
        "playbook_rules",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_rules_deleted_at"),
        "playbook_rules",
        ["deleted_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_table("playbook_rules")
    op.drop_table("playbooks")
