"""add legal corpus tables

Revision ID: legal_corpus_0805
Revises: widen_oauth2_0805
Create Date: 2026-08-05 20:27:53.061182

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "legal_corpus_0805"
down_revision = "widen_oauth2_0805"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "court_decisions",
        sa.Column("court", sa.String(length=32), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("decided_on", sa.Date(), nullable=False),
        sa.Column("chamber", sa.String(length=64), nullable=True),
        sa.Column("urn_lex", sa.String(length=256), nullable=True),
        sa.Column("ohadata_code", sa.String(length=32), nullable=True),
        sa.Column("source_url", sa.String(length=512), nullable=True),
        sa.Column("keyword_header", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("court_decisions_pkey")),
        sa.UniqueConstraint(
            "court",
            "number",
            "decided_on",
            name=op.f("court_decisions_court_number_decided_on_key"),
        ),
        sa.UniqueConstraint("urn_lex", name=op.f("court_decisions_urn_lex_key")),
    )
    op.create_index(
        op.f("ix_court_decisions_created_at"),
        "court_decisions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_court_decisions_decided_on"),
        "court_decisions",
        ["decided_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_court_decisions_deleted_at"),
        "court_decisions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_court_decisions_number"), "court_decisions", ["number"], unique=False
    )
    op.create_index(
        op.f("ix_court_decisions_ohadata_code"),
        "court_decisions",
        ["ohadata_code"],
        unique=False,
    )
    op.create_table(
        "legal_acts",
        sa.Column("akn_work_uri", sa.String(length=512), nullable=True),
        sa.Column("short_code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("jurisdiction", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("legal_acts_pkey")),
        sa.UniqueConstraint("akn_work_uri", name=op.f("legal_acts_akn_work_uri_key")),
    )
    op.create_index(
        op.f("ix_legal_acts_created_at"), "legal_acts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_legal_acts_deleted_at"), "legal_acts", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_legal_acts_short_code"), "legal_acts", ["short_code"], unique=False
    )
    op.create_table(
        "legal_act_versions",
        sa.Column("act_id", sa.Uuid(), nullable=False),
        sa.Column("akn_expression_uri", sa.String(length=512), nullable=True),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("adopted_on", sa.Date(), nullable=True),
        sa.Column("published_on", sa.Date(), nullable=True),
        sa.Column("gazette_reference", sa.Text(), nullable=True),
        sa.Column("in_force_from", sa.Date(), nullable=True),
        sa.Column("in_force_to", sa.Date(), nullable=True),
        sa.Column("transitional_rule", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["act_id"],
            ["legal_acts.id"],
            name=op.f("legal_act_versions_act_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("legal_act_versions_pkey")),
        sa.UniqueConstraint(
            "act_id", "label", name=op.f("legal_act_versions_act_id_label_key")
        ),
        sa.UniqueConstraint(
            "akn_expression_uri", name=op.f("legal_act_versions_akn_expression_uri_key")
        ),
    )
    op.create_index(
        op.f("ix_legal_act_versions_act_id"),
        "legal_act_versions",
        ["act_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_act_versions_created_at"),
        "legal_act_versions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_act_versions_deleted_at"),
        "legal_act_versions",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "legal_articles",
        sa.Column("act_version_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("sort_key", sa.Integer(), nullable=False),
        sa.Column("heading", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("akn_eid", sa.String(length=128), nullable=True),
        sa.Column("structure", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["act_version_id"],
            ["legal_act_versions.id"],
            name=op.f("legal_articles_act_version_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("legal_articles_pkey")),
        sa.UniqueConstraint(
            "act_version_id",
            "number",
            name=op.f("legal_articles_act_version_id_number_key"),
        ),
    )
    op.create_index(
        op.f("ix_legal_articles_act_version_id"),
        "legal_articles",
        ["act_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_articles_created_at"),
        "legal_articles",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_articles_deleted_at"),
        "legal_articles",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "court_decision_article_links",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("treatment", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("seed_source", sa.String(length=32), nullable=True),
        sa.Column("verified_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["legal_articles.id"],
            name=op.f("court_decision_article_links_article_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["court_decisions.id"],
            name=op.f("court_decision_article_links_decision_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
            name=op.f("court_decision_article_links_verified_by_user_id_fkey"),
            ondelete="set null",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("court_decision_article_links_pkey")),
        sa.UniqueConstraint(
            "decision_id",
            "article_id",
            name=op.f("court_decision_article_links_decision_id_article_id_key"),
        ),
    )
    op.create_index(
        op.f("ix_court_decision_article_links_article_id"),
        "court_decision_article_links",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_court_decision_article_links_created_at"),
        "court_decision_article_links",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_court_decision_article_links_decision_id"),
        "court_decision_article_links",
        ["decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_court_decision_article_links_deleted_at"),
        "court_decision_article_links",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_court_decision_article_links_status"),
        "court_decision_article_links",
        ["status"],
        unique=False,
    )
    op.create_table(
        "legal_article_equivalences",
        sa.Column("old_article_id", sa.Uuid(), nullable=True),
        sa.Column("new_article_id", sa.Uuid(), nullable=True),
        sa.Column("relation", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["new_article_id"],
            ["legal_articles.id"],
            name=op.f("legal_article_equivalences_new_article_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["old_article_id"],
            ["legal_articles.id"],
            name=op.f("legal_article_equivalences_old_article_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("legal_article_equivalences_pkey")),
        sa.UniqueConstraint(
            "old_article_id",
            "new_article_id",
            name=op.f("legal_article_equivalences_old_article_id_new_article_id_key"),
        ),
    )
    op.create_index(
        op.f("ix_legal_article_equivalences_created_at"),
        "legal_article_equivalences",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_article_equivalences_deleted_at"),
        "legal_article_equivalences",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_article_equivalences_new_article_id"),
        "legal_article_equivalences",
        ["new_article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_article_equivalences_old_article_id"),
        "legal_article_equivalences",
        ["old_article_id"],
        unique=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_legal_article_equivalences_old_article_id"),
        table_name="legal_article_equivalences",
    )
    op.drop_index(
        op.f("ix_legal_article_equivalences_new_article_id"),
        table_name="legal_article_equivalences",
    )
    op.drop_index(
        op.f("ix_legal_article_equivalences_deleted_at"),
        table_name="legal_article_equivalences",
    )
    op.drop_index(
        op.f("ix_legal_article_equivalences_created_at"),
        table_name="legal_article_equivalences",
    )
    op.drop_table("legal_article_equivalences")
    op.drop_index(
        op.f("ix_court_decision_article_links_status"),
        table_name="court_decision_article_links",
    )
    op.drop_index(
        op.f("ix_court_decision_article_links_deleted_at"),
        table_name="court_decision_article_links",
    )
    op.drop_index(
        op.f("ix_court_decision_article_links_decision_id"),
        table_name="court_decision_article_links",
    )
    op.drop_index(
        op.f("ix_court_decision_article_links_created_at"),
        table_name="court_decision_article_links",
    )
    op.drop_index(
        op.f("ix_court_decision_article_links_article_id"),
        table_name="court_decision_article_links",
    )
    op.drop_table("court_decision_article_links")
    op.drop_index(op.f("ix_legal_articles_deleted_at"), table_name="legal_articles")
    op.drop_index(op.f("ix_legal_articles_created_at"), table_name="legal_articles")
    op.drop_index(op.f("ix_legal_articles_act_version_id"), table_name="legal_articles")
    op.drop_table("legal_articles")
    op.drop_index(
        op.f("ix_legal_act_versions_deleted_at"), table_name="legal_act_versions"
    )
    op.drop_index(
        op.f("ix_legal_act_versions_created_at"), table_name="legal_act_versions"
    )
    op.drop_index(op.f("ix_legal_act_versions_act_id"), table_name="legal_act_versions")
    op.drop_table("legal_act_versions")
    op.drop_index(op.f("ix_legal_acts_short_code"), table_name="legal_acts")
    op.drop_index(op.f("ix_legal_acts_deleted_at"), table_name="legal_acts")
    op.drop_index(op.f("ix_legal_acts_created_at"), table_name="legal_acts")
    op.drop_table("legal_acts")
    op.drop_index(op.f("ix_court_decisions_ohadata_code"), table_name="court_decisions")
    op.drop_index(op.f("ix_court_decisions_number"), table_name="court_decisions")
    op.drop_index(op.f("ix_court_decisions_deleted_at"), table_name="court_decisions")
    op.drop_index(op.f("ix_court_decisions_decided_on"), table_name="court_decisions")
    op.drop_index(op.f("ix_court_decisions_created_at"), table_name="court_decisions")
    op.drop_table("court_decisions")
    # ### end Alembic commands ###
